import fs from 'node:fs';
import path from 'node:path';
export const searchTopics=[
 {slug:'companies',title:'IT Companies in Nepal & Nepali Tech Firms | Silicon Peaks',heading:'IT companies in Nepal. Nepali builders around the world.',description:'Explore IT companies operating in Nepal and technology businesses founded by Nepalis worldwide. Browse the open Silicon Peaks company directory.',label:'Company directory'},
 {slug:'startups',title:'Nepal Startup Ecosystem: Founders & Funding | Silicon Peaks',heading:'A guide to Nepal’s startup ecosystem.',description:'Discover Nepal’s startup ecosystem, Nepali founders, company stories, funding sources and community resources, with links to primary coverage.',label:'Startup ecosystem'},
 {slug:'investors',title:'Venture Capital in Nepal: Funds & Investors | Silicon Peaks',heading:'Venture capital in Nepal, and the investors connected to it.',description:'Explore venture capital firms, private capital and development finance in the Silicon Peaks directory, plus sourced examples of startup funding.',label:'Investor directory'}
];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const base='https://siliconpeaks.com';
const source={
 origin:'https://nepalitimes.com/bringing-silicon-peaks-to-nepal',
 security:'https://techcrunch.com/2025/08/21/raising-multiple-rounds-of-venture-capital-might-be-wrong-for-your-startup/',
 architect:'https://architectlabs.com/blog/seed',
 together:'https://www.together.fund/portfolio/architectlabs',
 niural:'https://www.prnewswire.com/news-releases/niural-launches-niural-ai-labs-and-grows-its-series-a-to-52-million-302806440.html',
 story:'https://venturebeat.com/security/securitypal-combines-ai-and-experts-in-nepal-to-speed-enterprise-security-questionnaires-by-87x-or-more/'
};
const link=(url,text)=>'<a href="'+esc(url)+'">'+esc(text)+'</a>';
function entries(root,list){
 return '<ul class="directory-list">'+list.map(e=>{
  const image=e.logo&&fs.existsSync(path.join(root,e.logo.replace(/^\//,'')))?'<img src="'+esc(e.logo)+'" alt="" width="32" height="32" loading="lazy" decoding="async"/>':'<span class="entry-initials" aria-hidden="true">'+esc(e.initials||e.name.slice(0,2))+'</span>';
  return '<li><a href="'+esc(e.url)+'" rel="noopener" target="_blank">'+image+'<span><strong>'+esc(e.name)+'</strong><small>'+esc(e.domain||new URL(e.url).hostname)+'</small></span><span class="entry-arrow" aria-hidden="true">↗</span></a></li>';
 }).join('')+'</ul>';
}
const funding=()=>'<div class="funding-stories"><article><span class="eyebrow">Enterprise security</span><h3>SecurityPal</h3><p>In an August 2025 interview, Pukar Hamal described a $21 million Series A raised in 2021, led by Craft Ventures. The coverage date and the date of the financing are different.</p>'+link(source.security,'Read the TechCrunch interview ↗')+'</article><article><span class="eyebrow">AI infrastructure</span><h3>Architect Labs</h3><p>Architect Labs announced a $24 million seed round in June 2026, led by Kindred Ventures, with Race Capital, TQ Ventures and Together Fund participating.</p>'+link(source.architect,'Read the company announcement ↗')+'<br/>'+link(source.together,'See Together Fund’s portfolio ↗')+'</article><article><span class="eyebrow">Finance & payroll</span><h3>Niural</h3><p>A June 2026 company release reported a $21 million extension, bringing its Series A total to $52 million. FOG Ventures and NewView Capital were named in the release.</p>'+link(source.niural,'Read the funding release ↗')+'</article></div>';
function content(root,topic,data){
 if(topic.slug==='companies')return '<p class="lead">An open directory of companies operating in Nepal and businesses founded by Nepalis abroad. The scope includes software, AI, financial services and other businesses connected to the ecosystem.</p><p>Use the official website linked from each entry to learn about its products, locations and current opportunities. Inclusion is a community listing, not a ranking, endorsement or claim that every company is headquartered in Nepal.</p><nav class="jump-links" aria-label="Company categories"><a href="#technology">Technology & business · '+data.companies.filter(e=>e.category==='Technology & business').length+'</a><a href="#listed">Public companies · 15</a></nav><section id="technology"><div class="section-heading"><span class="eyebrow">Directory</span><h2>Technology and business</h2><p>Companies in the original Silicon Peaks community directory, arranged alphabetically.</p></div>'+entries(root,data.companies.filter(e=>e.category==='Technology & business').sort((a,b)=>a.name.localeCompare(b.name)))+'</section><section id="listed"><div class="section-heading"><span class="eyebrow">NYSE & NASDAQ</span><h2>Public companies in the directory</h2><p>The community directory identifies these companies as having operations in Nepal. Follow the listing links for current company information.</p></div>'+entries(root,data.companies.filter(e=>e.category==='Public companies'))+'</section><section class="reading"><h2>Finding your place in the ecosystem</h2><p>If you are researching a company, start with its own website and recent coverage. For the wider context, read our '+link('/startups/','guide to Nepal’s startup ecosystem')+'. Founders looking for funding can explore the '+link('/investors/','venture capital and investor directory')+'.</p><p>For a correction or a new listing, email '+link('mailto:contribute@siliconpeaks.com','contribute@siliconpeaks.com')+' with the company website and a public source explaining its connection to Nepal.</p></section>';
 if(topic.slug==='startups')return '<p class="lead">Silicon Peaks connects the companies, founders, talent and capital associated with Nepal’s technology ecosystem. This guide is a starting point for exploring the community and the sources behind its stories.</p><nav class="jump-links" aria-label="Startup guide chapters"><a href="#name">The name</a><a href="#builders">The builders</a><a href="#funding">Funding</a><a href="#community">Community</a></nav><section id="name" class="reading"><span class="eyebrow">Origins</span><h2>What is Silicon Peaks?</h2><p>“Silicon Peaks” is an open-source name for the technology ecosystem emerging in Nepal’s Himalayan cities, starting with Kathmandu. Pukar Hamal, founder and CEO of SecurityPal, coined the name. The name is dedicated to the public domain under CC0, so anyone can use it.</p><p>'+link(source.origin,'Read the origin story in Nepali Times ↗')+'</p></section><section id="builders" class="reading"><span class="eyebrow">Companies & people</span><h2>Building from Nepal, working across borders</h2><p>The '+link('/companies/','company directory')+' brings together businesses operating in Nepal and companies founded by Nepalis elsewhere. Its scope is broader than startups alone: established technology teams, service businesses and publicly listed companies are also represented.</p><p>A July 2025 VentureBeat feature profiles SecurityPal’s Kathmandu operation and its combination of AI and human expertise in enterprise security reviews. It is one concrete example of a technology business connecting a Nepal-based team with global customers.</p><p>'+link(source.story,'Read the SecurityPal Kathmandu story ↗')+'</p></section><section id="funding"><div class="section-heading"><span class="eyebrow">Sourced examples</span><h2>Company funding stories</h2><p>These examples come from published interviews and company announcements. They are not an estimate of total funding in Nepal.</p></div>'+funding()+'</section><section id="community" class="reading"><span class="eyebrow">Explore further</span><h2>Meet the Silicon Peaks community</h2><p>Explore the '+link('/#universities','universities represented in the ecosystem')+', the '+link('/investors/','investor directory')+' and the '+link('/#press','press archive')+'. The homepage also preserves the community’s '+link('/#events','events and meetups section')+' and '+link('/#diaspora','Nepali diaspora overview')+'.</p><p>The original essays are community perspectives. Economic and flight-reach figures on the homepage remain labelled as community snapshots; this guide does not present them as independently verified statistics.</p><p>'+link('https://discord.gg/Z7y3ZhvNCC','Join the community on Discord ↗')+' or contact '+link('mailto:scale@siliconpeaks.com','scale@siliconpeaks.com')+'.</p></section>';
 return '<p class="lead">Explore the venture firms, private capital and development finance institutions listed by the Silicon Peaks community, alongside sourced examples of funding for companies in its ecosystem.</p><p>The directory includes both Nepal-focused and international organizations. Inclusion does not mean that a fund is based in Nepal, is currently investing there, or has invested in every company on the site. Check each fund’s own portfolio, mandate and application criteria.</p><nav class="jump-links" aria-label="Investor categories"><a href="#venture">Venture & private capital · 36</a><a href="#development">Development finance · 12</a><a href="#funding">Funding examples</a></nav><section id="venture"><div class="section-heading"><span class="eyebrow">Investor directory</span><h2>Venture and private capital</h2><p>Entrepreneurs First is included here as a talent investor and founder resource. The links lead to each organization’s own website.</p></div>'+entries(root,data.investors.filter(e=>e.category==='Venture & private capital'))+'</section><section id="development"><div class="section-heading"><span class="eyebrow">Institutional capital</span><h2>Development finance</h2><p>These institutions have different mandates and instruments from venture capital firms. Consult their official eligibility and program information.</p></div>'+entries(root,data.investors.filter(e=>e.category==='Development finance'))+'</section><section id="funding"><div class="section-heading"><span class="eyebrow">Primary coverage</span><h2>Who has funded companies in the ecosystem?</h2><p>Published funding announcements provide specific examples of investor participation.</p></div>'+funding()+'</section><section class="reading"><h2>Research before reaching out</h2><p>Review a fund’s stage, geography, sector and current portfolio before approaching it. An investor’s presence in a directory is a research lead, not an introduction or an offer of funding.</p><p>Continue with the '+link('/startups/','Nepal startup ecosystem guide')+' or browse '+link('/companies/','companies connected to Nepal')+'. Corrections with public sources are welcome at '+link('mailto:contribute@siliconpeaks.com','contribute@siliconpeaks.com')+'.</p></section>';
}
export function buildSearchPages(root,data,nav){
 for(const topic of searchTopics){
  const url=base+'/'+topic.slug+'/',list=topic.slug==='companies'?data.companies:topic.slug==='investors'?data.investors:null;
  const graph=[
   {'@type':'WebSite','@id':base+'/#website',url:base+'/',name:'Silicon Peaks',inLanguage:'en'},
   {'@type':list?'CollectionPage':'WebPage','@id':url+'#webpage',url,name:topic.title,description:topic.description,inLanguage:'en',isPartOf:{'@id':base+'/#website'},breadcrumb:{'@id':url+'#breadcrumbs'},...(list?{mainEntity:{'@id':url+'#directory'}}:{about:[{'@type':'Thing',name:'Nepal startup ecosystem'},{'@type':'Place',name:'Nepal'}]})},
   {'@type':'BreadcrumbList','@id':url+'#breadcrumbs',itemListElement:[{'@type':'ListItem',position:1,name:'Silicon Peaks',item:base+'/'},{'@type':'ListItem',position:2,name:topic.label,item:url}]}
  ];
  if(list)graph.push({'@type':'ItemList','@id':url+'#directory',name:topic.label,numberOfItems:list.length,itemListElement:list.map((e,i)=>({'@type':'ListItem',position:i+1,name:e.name,url:e.url}))});
  const schema=JSON.stringify({'@context':'https://schema.org','@graph':graph}).replaceAll('<','\\u003c');
  const header=nav.replaceAll('href="#','href="/#');
  const html='<!doctype html><html lang="en"><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/><title>'+esc(topic.title)+'</title><meta name="description" content="'+esc(topic.description)+'"/><meta name="robots" content="index,follow,max-image-preview:large"/><meta name="theme-color" content="#f5f8fb"/><link rel="canonical" href="'+url+'"/><meta property="og:type" content="website"/><meta property="og:site_name" content="Silicon Peaks"/><meta property="og:title" content="'+esc(topic.title)+'"/><meta property="og:description" content="'+esc(topic.description)+'"/><meta property="og:url" content="'+url+'"/><meta property="og:image" content="'+base+'/assets/images/social.jpg"/><meta property="og:image:width" content="1200"/><meta property="og:image:height" content="630"/><meta property="og:image:alt" content="Silicon Peaks, Nepal’s technology ecosystem"/><meta name="twitter:card" content="summary_large_image"/><meta name="twitter:title" content="'+esc(topic.title)+'"/><meta name="twitter:description" content="'+esc(topic.description)+'"/><meta name="twitter:image" content="'+base+'/assets/images/social.jpg"/><link href="/assets/favicon.ico" rel="icon" sizes="16x16 32x32 48x48"/><link href="/assets/favicon.svg" rel="icon" sizes="any" type="image/svg+xml"/><link href="/assets/apple-touch-icon.png" rel="apple-touch-icon" sizes="180x180"/><meta name="apple-mobile-web-app-title" content="Silicon Peaks"/><link rel="author" href="/humans.txt"/><link rel="alternate" type="text/plain" href="/llms.txt" title="Silicon Peaks overview"/><link rel="preload" as="font" href="/assets/fonts/geist-normal.woff2" type="font/woff2" crossorigin/><link rel="stylesheet" href="/assets/fonts.css"/><link rel="stylesheet" href="/assets/search-pages.css"/><script type="application/ld+json">'+schema+'</script></head><body class="light"><a class="skip-link" href="#main">Skip to content</a>'+header+'<main id="main"><nav class="breadcrumbs" aria-label="Breadcrumb"><a href="/">Silicon Peaks</a><span aria-hidden="true">/</span><span>'+esc(topic.label)+'</span></nav><header class="page-heading"><span class="eyebrow">Silicon Peaks · Open community directory</span><h1>'+esc(topic.heading)+'</h1></header>'+content(root,topic,data)+'<aside class="related"><h2>Continue exploring</h2>'+searchTopics.filter(t=>t.slug!==topic.slug).map(t=>link('/'+t.slug+'/',t.label+' →')).join('')+'</aside></main><footer><a class="footer-w" href="/">Silicon <em>Peaks</em></a><div>'+link('https://github.com/pchamal/siliconpeaks','Open source on GitHub ↗')+link('/llms.txt','LLMs.txt')+link('/sitemap.xml','Sitemap')+'</div></footer><script defer src="/assets/navigation.js"></script></body></html>';
  fs.mkdirSync(path.join(root,topic.slug),{recursive:true});
  fs.writeFileSync(path.join(root,topic.slug,'index.html'),html);
 }
}
